const jimp = require('jimp');
const fs = require('fs');

const typeLookup = {
  pound: "normal",
  karatechop: "fighting",
  doubleslap: "normal",
  cometpunch: "normal",
  megapunch: "normal",
  payday: "normal",
  firepunch: "fire",
  icepunch: "ice",
  thunderpunch: "electric",
  scratch: "normal",
  visegrip: "normal",
  guillotine: "normal",
  razorwind: "normal",
  swordsdance: "normal",
  cut: "normal",
  gust: "flying",
  wingattack: "flying",
  whirlwind: "normal",
  fly: "flying",
  bind: "normal",
  slam: "normal",
  vinewhip: "grass",
  stomp: "normal",
  doublekick: "fighting",
  megakick: "normal",
  jumpkick: "fighting",
  rollingkick: "fighting",
  sandattack: "ground",
  headbutt: "normal",
  hornattack: "normal",
  furyattack: "normal",
  horndrill: "normal",
  tackle: "normal",
  bodyslam: "normal",
  wrap: "normal",
  takedown: "normal",
  thrash: "normal",
  doubleedge: "normal",
  tailwhip: "normal",
  poisonsting: "poison",
  twineedle: "bug",
  pinmissile: "bug",
  leer: "normal",
  bite: "dark",
  growl: "normal",
  roar: "normal",
  sing: "normal",
  supersonic: "normal",
  sonicboom: "normal",
  disable: "normal",
  acid: "poison",
  ember: "fire",
  flamethrower: "fire",
  mist: "ice",
  watergun: "water",
  hydropump: "water",
  surf: "water",
  icebeam: "ice",
  blizzard: "ice",
  psybeam: "psychic",
  bubblebeam: "water",
  aurorabeam: "ice",
  hyperbeam: "normal",
  peck: "flying",
  drillpeck: "flying",
  submission: "fighting",
  lowkick: "fighting",
  counter: "fighting",
  seismictoss: "fighting",
  strength: "normal",
  absorb: "grass",
  megadrain: "grass",
  leechseed: "grass",
  growth: "normal",
  razorleaf: "grass",
  solarbeam: "grass",
  poisonpowder: "poison",
  stunspore: "grass",
  sleeppowder: "grass",
  petaldance: "grass",
  stringshot: "bug",
  dragonrage: "dragon",
  firespin: "fire",
  thundershock: "electric",
  thunderbolt: "electric",
  thunderwave: "electric",
  thunder: "electric",
  rockthrow: "rock",
  earthquake: "ground",
  fissure: "ground",
  dig: "ground",
  toxic: "poison",
  confusion: "psychic",
  psychic: "psychic",
  hypnosis: "psychic",
  meditate: "psychic",
  agility: "psychic",
  quickattack: "normal",
  rage: "normal",
  teleport: "psychic",
  nightshade: "ghost",
  mimic: "normal",
  screech: "normal",
  doubleteam: "normal",
  recover: "normal",
  harden: "normal",
  minimize: "normal",
  smokescreen: "normal",
  confuseray: "ghost",
  withdraw: "water",
  defensecurl: "normal",
  barrier: "psychic",
  lightscreen: "psychic",
  haze: "ice",
  reflect: "psychic",
  focusenergy: "normal",
  bide: "normal",
  metronome: "normal",
  mirrormove: "flying",
  selfdestruct: "normal",
  eggbomb: "normal",
  lick: "ghost",
  smog: "poison",
  sludge: "poison",
  boneclub: "ground",
  fireblast: "fire",
  waterfall: "water",
  clamp: "water",
  swift: "normal",
  skullbash: "normal",
  spikecannon: "normal",
  constrict: "normal",
  amnesia: "psychic",
  kinesis: "psychic",
  softboiled: "normal",
  highjumpkick: "fighting",
  glare: "normal",
  dreameater: "psychic",
  poisongas: "poison",
  barrage: "normal",
  leechlife: "bug",
  lovelykiss: "normal",
  skyattack: "flying",
  transform: "normal",
  bubble: "water",
  dizzypunch: "normal",
  spore: "grass",
  flash: "normal",
psywave: "psychic",
splash: "normal",
acidarmor: "poison",
crabhammer: "water",
explosion: "normal",
furyswipes: "normal",
bonemerang: "ground",
rest: "psychic",
rockslide: "rock",
hyperfang: "normal",
sharpen: "normal",
conversion: "normal",
triattack: "normal",
superfang: "normal",
slash: "normal",
substitute: "normal",
struggle: "normal",
sketch: "normal",
triplekick: "fighting",
thief: "dark",
spiderweb: "bug",
mindreader: "normal",
nightmare: "ghost",
flamewheel: "fire",
snore: "normal",
curse: "ghost",
flail: "normal",
conversion2: "normal",
aeroblast: "flying",
cottonspore: "grass",
reversal: "fighting",
spite: "ghost",
powdersnow: "ice",
protect: "normal",
machpunch: "fighting",
scaryface: "normal",
feintattack: "dark",
sweetkiss: "fairy",
bellydrum: "normal",
sludgebomb: "poison",
mudslap: "ground",
octazooka: "water",
spikes: "ground",
zapcannon: "electric",
foresight: "normal",
destinybond: "ghost",
perishsong: "normal",
icywind: "ice",
detect: "fighting",
bonerush: "ground",
lockon: "normal",
outrage: "dragon",
sandstorm: "rock",
gigadrain: "grass",
endure: "normal",
charm: "fairy",
rollout: "rock",
falseswipe: "normal",
swagger: "normal",
milkdrink: "normal",
spark: "electric",
furycutter: "bug",
steelwing: "steel",
meanlook: "normal",
attract: "normal",
sleeptalk: "normal",
healbell: "normal",
return: "normal",
present: "normal",
frustration: "normal",
safeguard: "normal",
painsplit: "normal",
sacredfire: "fire",
magnitude: "ground",
dynamicpunch: "fighting",
megahorn: "bug",
dragonbreath: "dragon",
batonpass: "normal",
encore: "normal",
pursuit: "dark",
rapidspin: "normal",
sweetscent: "normal",
irontail: "steel",
metalclaw: "steel",
vitalthrow: "fighting",
morningsun: "normal",
synthesis: "grass",
moonlight: "fairy",
hiddenpower: "normal",
crosschop: "fighting",
twister: "dragon",
raindance: "water",
sunnyday: "fire",
crunch: "dark",
mirrorcoat: "psychic",
psychup: "normal",
extremespeed: "normal",
ancientpower: "rock",
shadowball: "ghost",
futuresight: "psychic",
rocksmash: "fighting",
whirlpool: "water",
beatup: "dark",
fakeout: "normal",
uproar: "normal",
stockpile: "normal",
spitup: "normal",
swallow: "normal",
heatwave: "fire",
hail: "ice",
torment: "dark",
flatter: "dark",
willowisp: "fire",
memento: "dark",
facade: "normal",
focuspunch: "fighting",
smellingsalts: "normal",
followme: "normal",
naturepower: "normal",
charge: "electric",
taunt: "dark",
helpinghand: "normal",
trick: "psychic",
roleplay: "psychic",
wish: "normal",
assist: "normal",
ingrain: "grass",
superpower: "fighting",
magiccoat: "psychic",
recycle: "normal",
revenge: "fighting",
brickbreak: "fighting",
yawn: "normal",
knockoff: "dark",
endeavor: "normal",
eruption: "fire",
skillswap: "psychic",
imprison: "psychic",
refresh: "normal",
grudge: "ghost",
snatch: "dark",
secretpower: "normal",
dive: "water",
armthrust: "fighting",
camouflage: "normal",
tailglow: "bug",
lusterpurge: "psychic",
mistball: "psychic",
featherdance: "flying",
teeterdance: "normal",
blazekick: "fire",
mudsport: "ground",
iceball: "ice",
needlearm: "grass",
slackoff: "normal",
hypervoice: "normal",
poisonfang: "poison",
crushclaw: "normal",
blastburn: "fire",
hydrocannon: "water",
meteormash: "steel",
astonish: "ghost",
weatherball: "normal",
aromatherapy: "grass",
faketears: "dark",
aircutter: "flying",
overheat: "fire",
odorsleuth: "normal",
rocktomb: "rock",
silverwind: "bug",
metalsound: "steel",
grasswhistle: "grass",
tickle: "normal",
cosmicpower: "psychic",
waterspout: "water",
signalbeam: "bug",
shadowpunch: "ghost",
extrasensory: "psychic",
skyuppercut: "fighting",
sandtomb: "ground",
sheercold: "ice",
muddywater: "water",
bulletseed: "grass",
aerialace: "flying",
iciclespear: "ice",
irondefense: "steel",
block: "normal",
howl: "normal",
dragonclaw: "dragon",
frenzyplant: "grass",
bulkup: "fighting",
bounce: "flying",
mudshot: "ground",
poisontail: "poison",
covet: "normal",
volttackle: "electric",
magicalleaf: "grass",
watersport: "water",
calmmind: "psychic",
leafblade: "grass",
dragondance: "dragon",
rockblast: "rock",
shockwave: "electric",
waterpulse: "water",
doomdesire: "steel",
psychoboost: "psychic",
roost: "flying",
gravity: "psychic",
miracleeye: "psychic",
wakeupslap: "fighting",
hammerarm: "fighting",
gyroball: "steel",
healingwish: "psychic",
brine: "water",
naturalgift: "normal",
feint: "normal",
pluck: "flying",
tailwind: "flying",
acupressure: "normal",
metalburst: "steel",
uturn: "bug",
closecombat: "fighting",
payback: "dark",
assurance: "dark",
embargo: "dark",
fling: "dark",
psychoshift: "psychic",
trumpcard: "normal",
healblock: "psychic",
wringout: "normal",
powertrick: "psychic",
gastroacid: "poison",
luckychant: "normal",
mefirst: "normal",
copycat: "normal",
powerswap: "psychic",
guardswap: "psychic",
punishment: "dark",
lastresort: "normal",
worryseed: "grass",
suckerpunch: "dark",
toxicspikes: "poison",
heartswap: "psychic",
aquaring: "water",
magnetrise: "electric",
flareblitz: "fire",
forcepalm: "fighting",
aurasphere: "fighting",
rockpolish: "rock",
poisonjab: "poison",
darkpulse: "dark",
nightslash: "dark",
aquatail: "water",
seedbomb: "grass",
airslash: "flying",
xscissor: "bug",
bugbuzz: "bug",
dragonpulse: "dragon",
dragonrush: "dragon",
powergem: "rock",
drainpunch: "fighting",
vacuumwave: "fighting",
focusblast: "fighting",
energyball: "grass",
bravebird: "flying",
earthpower: "ground",
switcheroo: "dark",
gigaimpact: "normal",
nastyplot: "dark",
bulletpunch: "steel",
avalanche: "ice",
iceshard: "ice",
shadowclaw: "ghost",
thunderfang: "electric",
icefang: "ice",
firefang: "fire",
shadowsneak: "ghost",
mudbomb: "ground",
psychocut: "psychic",
zenheadbutt: "psychic",
mirrorshot: "steel",
flashcannon: "steel",
rockclimb: "normal",
defog: "flying",
trickroom: "psychic",
dracometeor: "dragon",
discharge: "electric",
lavaplume: "fire",
leafstorm: "grass",
powerwhip: "grass",
rockwrecker: "rock",
crosspoison: "poison",
gunkshot: "poison",
ironhead: "steel",
magnetbomb: "steel",
stoneedge: "rock",
captivate: "normal",
stealthrock: "rock",
grassknot: "grass",
chatter: "flying",
judgment: "normal",
bugbite: "bug",
chargebeam: "electric",
woodhammer: "grass",
aquajet: "water",
attackorder: "bug",
defendorder: "bug",
healorder: "bug",
headsmash: "rock",
doublehit: "normal",
roaroftime: "dragon",
spacialrend: "dragon",
lunardance: "psychic",
crushgrip: "normal",
magmastorm: "fire",
darkvoid: "dark",
seedflare: "grass",
ominouswind: "ghost",
shadowforce: "ghost",
honeclaws: "dark",
wideguard: "rock",
guardsplit: "psychic",
powersplit: "psychic",
wonderroom: "psychic",
psyshock: "psychic",
venoshock: "poison",
autotomize: "steel",
ragepowder: "bug",
telekinesis: "psychic",
magicroom: "psychic",
smackdown: "rock",
stormthrow: "fighting",
flameburst: "fire",
sludgewave: "poison",
quiverdance: "bug",
heavyslam: "steel",
synchronoise: "psychic",
electroball: "electric",
soak: "water",
flamecharge: "fire",
coil: "poison",
lowsweep: "fighting",
acidspray: "poison",
foulplay: "dark",
simplebeam: "normal",
entrainment: "normal",
afteryou: "normal",
round: "normal",
echoedvoice: "normal",
chipaway: "normal",
clearsmog: "poison",
storedpower: "psychic",
quickguard: "fighting",
allyswitch: "psychic",
scald: "water",
shellsmash: "normal",
healpulse: "psychic",
hex: "ghost",
skydrop: "flying",
shiftgear: "steel",
circlethrow: "fighting",
incinerate: "fire",
quash: "dark",
acrobatics: "flying",
reflecttype: "normal",
retaliate: "normal",
finalgambit: "fighting",
bestow: "normal",
inferno: "fire",
waterpledge: "water",
firepledge: "fire",
grasspledge: "grass",
voltswitch: "electric",
strugglebug: "bug",
bulldoze: "ground",
frostbreath: "ice",
dragontail: "dragon",
workup: "normal",
electroweb: "electric",
wildcharge: "electric",
drillrun: "ground",
dualchop: "dragon",
heartstamp: "psychic",
hornleech: "grass",
sacredsword: "fighting",
razorshell: "water",
heatcrash: "fire",
leaftornado: "grass",
steamroller: "bug",
cottonguard: "grass",
nightdaze: "dark",
psystrike: "psychic",
tailslap: "normal",
hurricane: "flying",
headcharge: "normal",
geargrind: "steel",
searingshot: "fire",
technoblast: "normal",
relicsong: "normal",
secretsword: "fighting",
glaciate: "ice",
boltstrike: "electric",
blueflare: "fire",
fierydance: "fire",
freezeshock: "ice",
iceburn: "ice",
snarl: "dark",
iciclecrash: "ice",
vcreate: "fire",
fusionflare: "fire",
fusionbolt: "electric",
flyingpress: "fighting",
matblock: "fighting",
belch: "poison",
rototiller: "ground",
stickyweb: "bug",
fellstinger: "bug",
phantomforce: "ghost",
trickortreat: "ghost",
nobleroar: "normal",
iondeluge: "electric",
paraboliccharge: "electric",
forestscurse: "grass",
petalblizzard: "grass",
freezedry: "ice",
disarmingvoice: "fairy",
partingshot: "dark",
topsyturvy: "dark",
drainingkiss: "fairy",
craftyshield: "fairy",
flowershield: "fairy",
grassyterrain: "grass",
mistyterrain: "fairy",
electrify: "electric",
playrough: "fairy",
fairywind: "fairy",
moonblast: "fairy",
boomburst: "normal",
fairylock: "fairy",
kingsshield: "steel",
playnice: "normal",
confide: "normal",
diamondstorm: "rock",
steameruption: "water",
hyperspacehole: "psychic",
watershuriken: "water",
mysticalfire: "fire",
spikyshield: "grass",
aromaticmist: "fairy",
eerieimpulse: "electric",
venomdrench: "poison",
powder: "bug",
geomancy: "fairy",
magneticflux: "electric",
happyhour: "normal",
electricterrain: "electric",
dazzlinggleam: "fairy",
celebrate: "normal",
holdhands: "normal",
babydolleyes: "fairy",
nuzzle: "electric",
holdback: "normal",
infestation: "bug",
poweruppunch: "fighting",
oblivionwing: "flying",
thousandarrows: "ground",
thousandwaves: "ground",
landswrath: "ground",
lightofruin: "fairy",
originpulse: "water",
precipiceblades: "ground",
dragonascent: "flying",
hyperspacefury: "dark",
breakneckblitz: "normal",
alloutpummeling: "fighting",
supersonicskystrike: "flying",
aciddownpour: "poison",
aciddownpour: "poison",
tectonicrage: "ground",
tectonicrage: "ground",
continentalcrush: "rock",
continentalcrush: "rock",
savagespinout: "bug",
neverendingnightmare: "ghost",
corkscrewcrash: "steel",
infernooverdrive: "fire",
hydrovortex: "water",
bloomdoom: "grass",
gigavolthavoc: "electric",
shatteredpsyche: "psychic",
subzeroslammer: "ice",
devastatingdrake: "dragon",
blackholeeclipse: "dark",
twinkletackle: "fairy",
catastropika: "electric",
shoreup: "ground",
firstimpression: "bug",
banefulbunker: "poison",
spiritshackle: "ghost",
darkestlariat: "dark",
sparklingaria: "water",
icehammer: "ice",
floralhealing: "fairy",
highhorsepower: "ground",
strengthsap: "grass",
solarblade: "grass",
leafage: "grass",
spotlight: "normal",
toxicthread: "poison",
laserfocus: "normal",
gearup: "steel",
throatchop: "dark",
pollenpuff: "bug",
anchorshot: "steel",
psychicterrain: "psychic",
lunge: "bug",
firelash: "fire",
powertrip: "dark",
burnup: "fire",
speedswap: "psychic",
smartstrike: "steel",
purify: "poison",
revelationdance: "normal",
coreenforcer: "dragon",
tropkick: "grass",
instruct: "psychic",
beakblast: "flying",
clangingscales: "dragon",
dragonhammer: "dragon",
brutalswing: "dark",
auroraveil: "ice",
sinisterarrowraid: "ghost",
maliciousmoonsault: "dark",
oceanicoperetta: "water",
guardianofalola: "fairy",
soulstealing7starstrike: "ghost",
stokedsparksurfer: "electric",
pulverizingpancake: "normal",
extremeevoboost: "normal",
genesissupernova: "psychic",
shelltrap: "fire",
fleurcannon: "fairy",
psychicfangs: "psychic",
stompingtantrum: "ground",
shadowbone: "ghost",
accelerock: "rock",
liquidation: "water",
prismaticlaser: "psychic",
spectralthief: "ghost",
sunsteelstrike: "steel",
moongeistbeam: "ghost",
tearfullook: "normal",
zingzap: "electric",
naturesmadness: "fairy",
multiattack: "normal",
mindblown: "fire",
plasmafists: "electric",
photongeyser: "psychic",
lightthatburnsthesky: "psychic",
searingsunrazesmash: "steel",
menacingmoonrazemaelstrom: "ghost",
letssnuggleforever: "fairy",
splinteredstormshards: "rock",
clangoroussoulblaze: "dragon",
zippyzap: "electric",
splishysplash: "water",
floatyfall: "flying",
pikapapow: "electric",
bouncybubble: "water",
buzzybuzz: "electric",
sizzlyslide: "fire",
glitzyglow: "psychic",
baddybad: "dark",
sappyseed: "grass",
freezyfrost: "ice",
sparklyswirl: "fairy",
veeveevolley: "normal",
doubleironbash: "steel",
maxguard: "normal",
dynamaxcannon: "dragon",
snipeshot: "water",
jawlock: "dark",
stuffcheeks: "normal",
noretreat: "fighting",
tarshot: "rock",
magicpowder: "psychic",
dragondarts: "dragon",
teatime: "normal",
octolock: "fighting",
boltbeak: "electric",
fishiousrend: "water",
courtchange: "normal",
maxflare: "fire",
maxflutterby: "bug",
maxlightning: "electric",
maxstrike: "normal",
maxknuckle: "fighting",
maxphantasm: "ghost",
maxhailstorm: "ice",
maxooze: "poison",
maxgeyser: "water",
maxairstream: "flying",
maxstarfall: "fairy",
maxwyrmwind: "dragon",
maxmindstorm: "psychic",
maxrockfall: "rock",
maxquake: "ground",
maxdarkness: "dark",
maxovergrowth: "grass",
maxsteelspike: "steel",
clangoroussoul: "dragon",
bodypress: "fighting",
decorate: "fairy",
drumbeating: "grass",
snaptrap: "grass",
pyroball: "fire",
behemothblade: "steel",
behemothbash: "steel",
aurawheel: "electric",
breakingswipe: "dragon",
branchpoke: "grass",
overdrive: "electric",
appleacid: "grass",
gravapple: "grass",
spiritbreak: "fairy",
strangesteam: "fairy",
lifedew: "water",
obstruct: "dark",
falsesurrender: "dark",
meteorassault: "fighting",
eternabeam: "dragon",
steelbeam: "steel",
expandingforce: "psychic",
steelroller: "steel",
scaleshot: "dragon",
meteorbeam: "rock",
shellsidearm: "poison",
mistyexplosion: "fairy",
grassyglide: "grass",
risingvoltage: "electric",
terrainpulse: "normal",
skittersmack: "bug",
burningjealousy: "fire",
lashout: "dark",
poltergeist: "ghost",
corrosivegas: "poison",
coaching: "fighting",
flipturn: "water",
tripleaxel: "ice",
dualwingbeat: "flying",
scorchingsands: "ground",
junglehealing: "grass",
wickedblow: "dark",
surgingstrikes: "water",
thundercage: "electric",
dragonenergy: "dragon",
freezingglare: "psychic",
fierywrath: "dark",
thunderouskick: "fighting",
glaciallance: "ice",
astralbarrage: "ghost",
eeriespell: "psychic",
};

const typeMap = (type) => typeLookup[type] || "???";

async function crop() {
  for(let i = 0; i < string.length; i++){
    let imgstring = 'images/fonttest/' + string.codePointAt(i) + '.png';
    const image = await jimp.read('images/fonttest/capitals.png');
    image.crop(i * 6, 0, 6, 14).write(imgstring);
 }
}

async function constructDarkText(input){
  if(!(typeof(input) === "string"))
    return;
  else {
    const letters = [];
    const widths = [];
    for(let i = 0; i < input.length; i++){
      let imgPath = 'images/fonts/dark/' + input.codePointAt(i) + '.png';
      if(fs.existsSync(imgPath)){
        const image = await jimp.read(imgPath);
        await widths.push(image.bitmap.width);
        await letters.push(image);
      }
      else{
        const image = await jimp.read('images/fonts/dark/32.png');
        await widths.push(image.bitmap.width);
        await letters.push(image);
      }
    }

    let sumWidths = 0;
    for(let i = 0; i < widths.length; i++){
      sumWidths += widths[i];
    }

    let newTextImage = new jimp(sumWidths,14)
    let curWidth = 0;
    for(let i = 0; i < letters.length; i++){
      await newTextImage.composite(letters[i], curWidth, 0);
      curWidth += widths[i];
    }

    await newTextImage.writeAsync('images/temp/' + input + '.png');
    return newTextImage;
  }
}

//Clears the temporary files that are used in constructing the output.
//Should only be called after construction is complete.
function clearTemp(){
  fs.readdir('images/temp/', (err, files) => {
    if (err) {
      throw err;
    }
    else{
      for(let i = 0; i < files.length; i++){
        fs.unlink('images/temp/' + files[i], (err) => {
          if (err) {
            throw err;
          }
          else{
            console.log("File is deleted.");
          }
        });
      }
    }
  });
}

//Accepts an array of inputs, if they aren't in the correct order
//stuff won't end well. The intended order and types are listed below
//inputs[0]: nickname (string)
//inputs[1]: species (string)
//inputs[2]: item (string)
//inputs[3]: gender (string)
//inputs[4]: ability (string)
//inputs[5]: isShiny (boolean)
//inputs[6]: nature (string)
//inputs[7]: level (int)
//inputs[8]: moves (array of strings)
//inputs[9]: EVs (array of ints)
//inputs[10]: IVs (array of ints)
async function constructImage(inputs){
  var itemImg;
  var itemIcon;

  if(inputs[2]){
    itemImg = await constructDarkText(inputs[2].toUpperCase());
    if (fs.existsSync('images/items/' + inputs[2].replace(/\s+/g, '').toLowerCase() + '.png')){
      itemIcon = await jimp.read('images/items/' + inputs[2].replace(/\s+/g, '').toLowerCase() + '.png');
    }
    else{
      itemIcon = await jimp.read('images/items/error.png');
    }
  }
  else{
    itemImg = await constructDarkText('NONE');
    itemIcon = await jimp.read('images/items/noitem.png');
  }

  const abilityImg = await constructDarkText(inputs[4].toUpperCase());
  const moveImgs = [];
  for(let i = 0; i < inputs[8].length; i++){
    moveImgs.push(await constructDarkText(inputs[8][i].toUpperCase()));
  }

  var base = new jimp(240,160);

  if(inputs[5]){
    base = await jimp.read('images/shinybackground.png');
  }
  else {
    base = await jimp.read('images/background.png');
  }
  await base.composite(itemImg, 7, 113);
  await base.composite(abilityImg, 7, 141);
  for(let i = 0; i < moveImgs.length; i++){
    await base.composite(moveImgs[i], 131, 104 + i*13);
    var typeImg = await jimp.read('images/types/' + typeMap(inputs[8][i].replace(/[^0-9a-z]/gi, '').toLowerCase()) + '.png');
    await base.composite(typeImg, 94, 105 + i*13);
  }
  await base.composite(itemIcon, 115 - itemIcon.bitmap.width, 93 - itemIcon.bitmap.height);


  await base.write('images/temp/bigtest.png');

}

const testInputs = [];
testInputs.push("HTV-2");
testInputs.push("Whimsicott");
testInputs.push('Mental Herb');
testInputs.push("M");
testInputs.push("Prankster");
testInputs.push(true);
testInputs.push("Timid");
testInputs.push(100);
const moves = [];
moves.push("Moonblast");
moves.push("Tailwind");
moves.push("Taunt");
moves.push("Helping Hand");
testInputs.push(moves);

const evs = [];
evs.push(31);
evs.push(0);
evs.push(31);
evs.push(31);
evs.push(31);
evs.push(31);

testInputs.push(evs);

const ivs = [];
ivs.push(252);
ivs.push(0);
ivs.push(0);
ivs.push(4);
ivs.push(0);
ivs.push(252);

testInputs.push(ivs);


console.log(testInputs);

constructImage(testInputs);
